// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Bl0sX3lMORlr3VSLBOgEhXGqWJ9scfo',
    appId: '1:321256027802:web:8f630d467a835cfd56d123',
    messagingSenderId: '321256027802',
    projectId: 'bookmeapp-6f197',
    authDomain: 'bookmeapp-6f197.firebaseapp.com',
    storageBucket: 'bookmeapp-6f197.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2zLvGZUB5qwc_FTYQl8mZPvDbJUVtRSo',
    appId: '1:321256027802:android:5a1881937879b6f956d123',
    messagingSenderId: '321256027802',
    projectId: 'bookmeapp-6f197',
    storageBucket: 'bookmeapp-6f197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxbSLIeoe_qE1DXTj4wHPckyMDULPNYeA',
    appId: '1:321256027802:ios:74028019b0daa57456d123',
    messagingSenderId: '321256027802',
    projectId: 'bookmeapp-6f197',
    storageBucket: 'bookmeapp-6f197.firebasestorage.app',
    iosBundleId: 'com.example.bookmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxbSLIeoe_qE1DXTj4wHPckyMDULPNYeA',
    appId: '1:321256027802:ios:74028019b0daa57456d123',
    messagingSenderId: '321256027802',
    projectId: 'bookmeapp-6f197',
    storageBucket: 'bookmeapp-6f197.firebasestorage.app',
    iosBundleId: 'com.example.bookmeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Bl0sX3lMORlr3VSLBOgEhXGqWJ9scfo',
    appId: '1:321256027802:web:30c48313e0a4f65356d123',
    messagingSenderId: '321256027802',
    projectId: 'bookmeapp-6f197',
    authDomain: 'bookmeapp-6f197.firebaseapp.com',
    storageBucket: 'bookmeapp-6f197.firebasestorage.app',
  );

}